type Hotel {
    id: String!
    name: String!
    address: String!
    city: String!
    country: String!
    stars: Int
    services: [String]
}

type Query {
    hotel(id: ID!): Hotel @gql(url: "http://localhost:8102/graphql", queryName: "hotel"),
    hotels: [Hotel] @gql(url: "http://localhost:8102/graphql", queryName: "hotels")
}
