type Order {
    id: ID!
    customer: Customer!
        @http(url: "http://customer-api/customer/:customerId")
    hotel: Hotel!
        @gql(url: "http://hotel-api:3000/graphql", queryName: "hotel", arguments: "id:\"{source.hotelId}\"")
    startDate: String!
    endDate: String!
    adults: Int!
    children: Int
    city: String!
    country: String!
}

type Customer {
    orders: [Order!] @http(url: "http://order-api:3000/customerOrders/:id")
}

type Hotel {
    orders: [Order!] @http(url: "http://order-api:3000/hotelOrders/:id")
}