FROM golang:latest as base
RUN mkdir /app 
WORKDIR /app

ADD go.mod /app/go.mod
ADD go.sum /app/go.sum

RUN go mod download
ADD . /app/ 

FROM base as build
RUN go build -o main . 

FROM build as tests
RUN go test ./...

FROM build as release
CMD ["/app/main"]