// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agogos.proto

package agogos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscribeParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeParams) Reset()         { *m = SubscribeParams{} }
func (m *SubscribeParams) String() string { return proto.CompactTextString(m) }
func (*SubscribeParams) ProtoMessage()    {}
func (*SubscribeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1ae9729f0092b, []int{0}
}

func (m *SubscribeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeParams.Unmarshal(m, b)
}
func (m *SubscribeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeParams.Marshal(b, m, deterministic)
}
func (m *SubscribeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeParams.Merge(m, src)
}
func (m *SubscribeParams) XXX_Size() int {
	return xxx_messageInfo_SubscribeParams.Size(m)
}
func (m *SubscribeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeParams.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeParams proto.InternalMessageInfo

type ConfigurationMessage struct {
	Schema                  *Schema                    `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Upstreams               []*Upstream                `protobuf:"bytes,2,rep,name=upstreams,proto3" json:"upstreams,omitempty"`
	UpstreamAuthCredentials []*UpstreamAuthCredentials `protobuf:"bytes,3,rep,name=upstream_auth_credentials,json=upstreamAuthCredentials,proto3" json:"upstream_auth_credentials,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                   `json:"-"`
	XXX_unrecognized        []byte                     `json:"-"`
	XXX_sizecache           int32                      `json:"-"`
}

func (m *ConfigurationMessage) Reset()         { *m = ConfigurationMessage{} }
func (m *ConfigurationMessage) String() string { return proto.CompactTextString(m) }
func (*ConfigurationMessage) ProtoMessage()    {}
func (*ConfigurationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1ae9729f0092b, []int{1}
}

func (m *ConfigurationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationMessage.Unmarshal(m, b)
}
func (m *ConfigurationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationMessage.Marshal(b, m, deterministic)
}
func (m *ConfigurationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationMessage.Merge(m, src)
}
func (m *ConfigurationMessage) XXX_Size() int {
	return xxx_messageInfo_ConfigurationMessage.Size(m)
}
func (m *ConfigurationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationMessage proto.InternalMessageInfo

func (m *ConfigurationMessage) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *ConfigurationMessage) GetUpstreams() []*Upstream {
	if m != nil {
		return m.Upstreams
	}
	return nil
}

func (m *ConfigurationMessage) GetUpstreamAuthCredentials() []*UpstreamAuthCredentials {
	if m != nil {
		return m.UpstreamAuthCredentials
	}
	return nil
}

type Schema struct {
	Definition           string   `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1ae9729f0092b, []int{2}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type Upstream struct {
	Host                 string                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Auth                 *UpstreamAuthentication `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Upstream) Reset()         { *m = Upstream{} }
func (m *Upstream) String() string { return proto.CompactTextString(m) }
func (*Upstream) ProtoMessage()    {}
func (*Upstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1ae9729f0092b, []int{3}
}

func (m *Upstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Upstream.Unmarshal(m, b)
}
func (m *Upstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Upstream.Marshal(b, m, deterministic)
}
func (m *Upstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upstream.Merge(m, src)
}
func (m *Upstream) XXX_Size() int {
	return xxx_messageInfo_Upstream.Size(m)
}
func (m *Upstream) XXX_DiscardUnknown() {
	xxx_messageInfo_Upstream.DiscardUnknown(m)
}

var xxx_messageInfo_Upstream proto.InternalMessageInfo

func (m *Upstream) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Upstream) GetAuth() *UpstreamAuthentication {
	if m != nil {
		return m.Auth
	}
	return nil
}

type UpstreamAuthentication struct {
	AuthType             string   `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpstreamAuthentication) Reset()         { *m = UpstreamAuthentication{} }
func (m *UpstreamAuthentication) String() string { return proto.CompactTextString(m) }
func (*UpstreamAuthentication) ProtoMessage()    {}
func (*UpstreamAuthentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1ae9729f0092b, []int{4}
}

func (m *UpstreamAuthentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamAuthentication.Unmarshal(m, b)
}
func (m *UpstreamAuthentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamAuthentication.Marshal(b, m, deterministic)
}
func (m *UpstreamAuthentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamAuthentication.Merge(m, src)
}
func (m *UpstreamAuthentication) XXX_Size() int {
	return xxx_messageInfo_UpstreamAuthentication.Size(m)
}
func (m *UpstreamAuthentication) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamAuthentication.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamAuthentication proto.InternalMessageInfo

func (m *UpstreamAuthentication) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

func (m *UpstreamAuthentication) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *UpstreamAuthentication) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type UpstreamAuthCredentials struct {
	AuthType             string   `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpstreamAuthCredentials) Reset()         { *m = UpstreamAuthCredentials{} }
func (m *UpstreamAuthCredentials) String() string { return proto.CompactTextString(m) }
func (*UpstreamAuthCredentials) ProtoMessage()    {}
func (*UpstreamAuthCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8a1ae9729f0092b, []int{5}
}

func (m *UpstreamAuthCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamAuthCredentials.Unmarshal(m, b)
}
func (m *UpstreamAuthCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamAuthCredentials.Marshal(b, m, deterministic)
}
func (m *UpstreamAuthCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamAuthCredentials.Merge(m, src)
}
func (m *UpstreamAuthCredentials) XXX_Size() int {
	return xxx_messageInfo_UpstreamAuthCredentials.Size(m)
}
func (m *UpstreamAuthCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamAuthCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamAuthCredentials proto.InternalMessageInfo

func (m *UpstreamAuthCredentials) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

func (m *UpstreamAuthCredentials) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *UpstreamAuthCredentials) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *UpstreamAuthCredentials) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func init() {
	proto.RegisterType((*SubscribeParams)(nil), "agogos.SubscribeParams")
	proto.RegisterType((*ConfigurationMessage)(nil), "agogos.ConfigurationMessage")
	proto.RegisterType((*Schema)(nil), "agogos.Schema")
	proto.RegisterType((*Upstream)(nil), "agogos.Upstream")
	proto.RegisterType((*UpstreamAuthentication)(nil), "agogos.UpstreamAuthentication")
	proto.RegisterType((*UpstreamAuthCredentials)(nil), "agogos.UpstreamAuthCredentials")
}

func init() { proto.RegisterFile("agogos.proto", fileDescriptor_f8a1ae9729f0092b) }

var fileDescriptor_f8a1ae9729f0092b = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xfd, 0xd2, 0xf6, 0x0b, 0xc9, 0x6d, 0xbf, 0x1f, 0x87, 0x62, 0xa3, 0x2d, 0xb5, 0x44, 0x90,
	0xae, 0x8a, 0xc4, 0x27, 0x90, 0x82, 0xe0, 0x42, 0x90, 0xa9, 0xae, 0x5c, 0x94, 0x69, 0x72, 0x9b,
	0x0c, 0xb4, 0x99, 0x30, 0x33, 0x59, 0xe4, 0x45, 0x7c, 0x29, 0x5f, 0x4a, 0x32, 0x49, 0x5a, 0x95,
	0xb8, 0x72, 0x37, 0xf7, 0x9c, 0x33, 0x73, 0xee, 0x19, 0x0e, 0x0c, 0x58, 0x2c, 0x62, 0xa1, 0x16,
	0x99, 0x14, 0x5a, 0x10, 0xbb, 0x9a, 0xfc, 0x13, 0xf8, 0xb7, 0xca, 0x37, 0x2a, 0x94, 0x7c, 0x83,
	0x8f, 0x4c, 0xb2, 0xbd, 0xf2, 0xdf, 0x2c, 0x18, 0x2e, 0x45, 0xba, 0xe5, 0x71, 0x2e, 0x99, 0xe6,
	0x22, 0x7d, 0x40, 0xa5, 0x58, 0x8c, 0xe4, 0x0a, 0x6c, 0x15, 0x26, 0xb8, 0x67, 0x9e, 0x35, 0xb3,
	0xe6, 0xfd, 0xe0, 0xef, 0xa2, 0x7e, 0x72, 0x65, 0x50, 0x5a, 0xb3, 0x64, 0x01, 0x6e, 0x9e, 0x29,
	0x2d, 0x91, 0xed, 0x95, 0xd7, 0x99, 0x75, 0xe7, 0xfd, 0xe0, 0x7f, 0x23, 0x7d, 0xae, 0x09, 0x7a,
	0x94, 0x90, 0x17, 0x38, 0x6b, 0x86, 0x35, 0xcb, 0x75, 0xb2, 0x0e, 0x25, 0x46, 0x98, 0x6a, 0xce,
	0x76, 0xca, 0xeb, 0x9a, 0xfb, 0x17, 0x5f, 0xef, 0xdf, 0xe6, 0x3a, 0x59, 0x1e, 0x65, 0x74, 0x94,
	0xb7, 0x13, 0xfe, 0x1c, 0xec, 0x6a, 0x3d, 0x32, 0x05, 0x88, 0x70, 0xcb, 0x53, 0x5e, 0x66, 0x32,
	0x11, 0x5c, 0xfa, 0x01, 0xf1, 0x29, 0x38, 0xcd, 0xeb, 0x84, 0x40, 0x2f, 0x11, 0x4a, 0xd7, 0x2a,
	0x73, 0x26, 0x01, 0xf4, 0xca, 0xed, 0xbc, 0x8e, 0x09, 0x3f, 0x6d, 0xdb, 0xa8, 0x34, 0x0d, 0xcd,
	0x9f, 0x51, 0xa3, 0xf5, 0x39, 0x9c, 0xb6, 0xf3, 0x64, 0x0c, 0xae, 0xc9, 0xaa, 0x8b, 0x0c, 0x6b,
	0x1b, 0xa7, 0x04, 0x9e, 0x8a, 0x0c, 0xc9, 0xa4, 0x22, 0x85, 0xe4, 0xba, 0x30, 0x7e, 0x2e, 0x3d,
	0x02, 0x64, 0x08, 0xbf, 0x55, 0x28, 0x32, 0xf4, 0xba, 0x86, 0xa9, 0x06, 0xff, 0xd5, 0x82, 0xd1,
	0x37, 0xbf, 0xf3, 0x13, 0xb3, 0x31, 0xb8, 0xe1, 0x8e, 0x63, 0xaa, 0xd7, 0x3c, 0xaa, 0x0d, 0x9d,
	0x0a, 0xb8, 0x8f, 0xc8, 0x25, 0xfc, 0xa9, 0x49, 0x85, 0xa1, 0x44, 0xed, 0xf5, 0x8c, 0x60, 0x50,
	0x81, 0x2b, 0x83, 0x05, 0x14, 0x1c, 0x8a, 0x31, 0x57, 0x5a, 0x16, 0xe4, 0x0e, 0xdc, 0x43, 0xdd,
	0xc8, 0xe8, 0xd0, 0x9f, 0xcf, 0x0d, 0x3c, 0x9f, 0x34, 0x44, 0x5b, 0x0d, 0xfd, 0x5f, 0xd7, 0xd6,
	0xc6, 0x36, 0x2d, 0xbe, 0x79, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x46, 0xe8, 0x24, 0xd5, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	Subscribe(ctx context.Context, in *SubscribeParams, opts ...grpc.CallOption) (Registry_SubscribeClient, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) Subscribe(ctx context.Context, in *SubscribeParams, opts ...grpc.CallOption) (Registry_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Registry_serviceDesc.Streams[0], "/agogos.Registry/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &registrySubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_SubscribeClient interface {
	Recv() (*ConfigurationMessage, error)
	grpc.ClientStream
}

type registrySubscribeClient struct {
	grpc.ClientStream
}

func (x *registrySubscribeClient) Recv() (*ConfigurationMessage, error) {
	m := new(ConfigurationMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	Subscribe(*SubscribeParams, Registry_SubscribeServer) error
}

// UnimplementedRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedRegistryServer struct {
}

func (*UnimplementedRegistryServer) Subscribe(req *SubscribeParams, srv Registry_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).Subscribe(m, &registrySubscribeServer{stream})
}

type Registry_SubscribeServer interface {
	Send(*ConfigurationMessage) error
	grpc.ServerStream
}

type registrySubscribeServer struct {
	grpc.ServerStream
}

func (x *registrySubscribeServer) Send(m *ConfigurationMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agogos.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Registry_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agogos.proto",
}
