// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gql_configuration.proto

package gqlconfig

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GqlConfigurationSubscribeParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GqlConfigurationSubscribeParams) Reset()         { *m = GqlConfigurationSubscribeParams{} }
func (m *GqlConfigurationSubscribeParams) String() string { return proto.CompactTextString(m) }
func (*GqlConfigurationSubscribeParams) ProtoMessage()    {}
func (*GqlConfigurationSubscribeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c11b78add49bf2c8, []int{0}
}

func (m *GqlConfigurationSubscribeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GqlConfigurationSubscribeParams.Unmarshal(m, b)
}
func (m *GqlConfigurationSubscribeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GqlConfigurationSubscribeParams.Marshal(b, m, deterministic)
}
func (m *GqlConfigurationSubscribeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GqlConfigurationSubscribeParams.Merge(m, src)
}
func (m *GqlConfigurationSubscribeParams) XXX_Size() int {
	return xxx_messageInfo_GqlConfigurationSubscribeParams.Size(m)
}
func (m *GqlConfigurationSubscribeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GqlConfigurationSubscribeParams.DiscardUnknown(m)
}

var xxx_messageInfo_GqlConfigurationSubscribeParams proto.InternalMessageInfo

type GqlConfigurationMessage struct {
	Schema               *GqlSchema         `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Endpoints            []*GqlEndpoint     `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	AuthProviders        []*GqlAuthProvider `protobuf:"bytes,3,rep,name=auth_providers,json=authProviders,proto3" json:"auth_providers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GqlConfigurationMessage) Reset()         { *m = GqlConfigurationMessage{} }
func (m *GqlConfigurationMessage) String() string { return proto.CompactTextString(m) }
func (*GqlConfigurationMessage) ProtoMessage()    {}
func (*GqlConfigurationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c11b78add49bf2c8, []int{1}
}

func (m *GqlConfigurationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GqlConfigurationMessage.Unmarshal(m, b)
}
func (m *GqlConfigurationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GqlConfigurationMessage.Marshal(b, m, deterministic)
}
func (m *GqlConfigurationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GqlConfigurationMessage.Merge(m, src)
}
func (m *GqlConfigurationMessage) XXX_Size() int {
	return xxx_messageInfo_GqlConfigurationMessage.Size(m)
}
func (m *GqlConfigurationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GqlConfigurationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GqlConfigurationMessage proto.InternalMessageInfo

func (m *GqlConfigurationMessage) GetSchema() *GqlSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *GqlConfigurationMessage) GetEndpoints() []*GqlEndpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *GqlConfigurationMessage) GetAuthProviders() []*GqlAuthProvider {
	if m != nil {
		return m.AuthProviders
	}
	return nil
}

type GqlSchema struct {
	Gql                  string   `protobuf:"bytes,1,opt,name=gql,proto3" json:"gql,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GqlSchema) Reset()         { *m = GqlSchema{} }
func (m *GqlSchema) String() string { return proto.CompactTextString(m) }
func (*GqlSchema) ProtoMessage()    {}
func (*GqlSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_c11b78add49bf2c8, []int{2}
}

func (m *GqlSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GqlSchema.Unmarshal(m, b)
}
func (m *GqlSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GqlSchema.Marshal(b, m, deterministic)
}
func (m *GqlSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GqlSchema.Merge(m, src)
}
func (m *GqlSchema) XXX_Size() int {
	return xxx_messageInfo_GqlSchema.Size(m)
}
func (m *GqlSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_GqlSchema.DiscardUnknown(m)
}

var xxx_messageInfo_GqlSchema proto.InternalMessageInfo

func (m *GqlSchema) GetGql() string {
	if m != nil {
		return m.Gql
	}
	return ""
}

type GqlEndpoint struct {
	Host                 string                     `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Auth                 *GqlEndpointAuthentication `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GqlEndpoint) Reset()         { *m = GqlEndpoint{} }
func (m *GqlEndpoint) String() string { return proto.CompactTextString(m) }
func (*GqlEndpoint) ProtoMessage()    {}
func (*GqlEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_c11b78add49bf2c8, []int{3}
}

func (m *GqlEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GqlEndpoint.Unmarshal(m, b)
}
func (m *GqlEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GqlEndpoint.Marshal(b, m, deterministic)
}
func (m *GqlEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GqlEndpoint.Merge(m, src)
}
func (m *GqlEndpoint) XXX_Size() int {
	return xxx_messageInfo_GqlEndpoint.Size(m)
}
func (m *GqlEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_GqlEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_GqlEndpoint proto.InternalMessageInfo

func (m *GqlEndpoint) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *GqlEndpoint) GetAuth() *GqlEndpointAuthentication {
	if m != nil {
		return m.Auth
	}
	return nil
}

type GqlEndpointAuthentication struct {
	AuthType             string   `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GqlEndpointAuthentication) Reset()         { *m = GqlEndpointAuthentication{} }
func (m *GqlEndpointAuthentication) String() string { return proto.CompactTextString(m) }
func (*GqlEndpointAuthentication) ProtoMessage()    {}
func (*GqlEndpointAuthentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_c11b78add49bf2c8, []int{4}
}

func (m *GqlEndpointAuthentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GqlEndpointAuthentication.Unmarshal(m, b)
}
func (m *GqlEndpointAuthentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GqlEndpointAuthentication.Marshal(b, m, deterministic)
}
func (m *GqlEndpointAuthentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GqlEndpointAuthentication.Merge(m, src)
}
func (m *GqlEndpointAuthentication) XXX_Size() int {
	return xxx_messageInfo_GqlEndpointAuthentication.Size(m)
}
func (m *GqlEndpointAuthentication) XXX_DiscardUnknown() {
	xxx_messageInfo_GqlEndpointAuthentication.DiscardUnknown(m)
}

var xxx_messageInfo_GqlEndpointAuthentication proto.InternalMessageInfo

func (m *GqlEndpointAuthentication) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

func (m *GqlEndpointAuthentication) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *GqlEndpointAuthentication) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

// TODO: Use "oneof" keyword to declare several types of Auth Providers
type GqlAuthProvider struct {
	AuthType             string   `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GqlAuthProvider) Reset()         { *m = GqlAuthProvider{} }
func (m *GqlAuthProvider) String() string { return proto.CompactTextString(m) }
func (*GqlAuthProvider) ProtoMessage()    {}
func (*GqlAuthProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_c11b78add49bf2c8, []int{5}
}

func (m *GqlAuthProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GqlAuthProvider.Unmarshal(m, b)
}
func (m *GqlAuthProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GqlAuthProvider.Marshal(b, m, deterministic)
}
func (m *GqlAuthProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GqlAuthProvider.Merge(m, src)
}
func (m *GqlAuthProvider) XXX_Size() int {
	return xxx_messageInfo_GqlAuthProvider.Size(m)
}
func (m *GqlAuthProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_GqlAuthProvider.DiscardUnknown(m)
}

var xxx_messageInfo_GqlAuthProvider proto.InternalMessageInfo

func (m *GqlAuthProvider) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

func (m *GqlAuthProvider) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *GqlAuthProvider) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GqlAuthProvider) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func init() {
	proto.RegisterType((*GqlConfigurationSubscribeParams)(nil), "gqlconfig.GqlConfigurationSubscribeParams")
	proto.RegisterType((*GqlConfigurationMessage)(nil), "gqlconfig.GqlConfigurationMessage")
	proto.RegisterType((*GqlSchema)(nil), "gqlconfig.GqlSchema")
	proto.RegisterType((*GqlEndpoint)(nil), "gqlconfig.GqlEndpoint")
	proto.RegisterType((*GqlEndpointAuthentication)(nil), "gqlconfig.GqlEndpointAuthentication")
	proto.RegisterType((*GqlAuthProvider)(nil), "gqlconfig.GqlAuthProvider")
}

func init() { proto.RegisterFile("gql_configuration.proto", fileDescriptor_c11b78add49bf2c8) }

var fileDescriptor_c11b78add49bf2c8 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0xd7, 0x71, 0x36, 0x44, 0x93, 0xcd, 0x6e, 0x10, 0x61, 0xe3, 0x4d, 0x76, 0xd9, 0x54,
	0xed, 0x21, 0x94, 0x12, 0x4a, 0xda, 0x43, 0xaf, 0xa1, 0x94, 0xd0, 0x43, 0x21, 0x38, 0xbd, 0xf5,
	0x60, 0x1c, 0x5b, 0xb5, 0x05, 0x8e, 0x65, 0x4b, 0x72, 0x21, 0x2f, 0xd1, 0x67, 0xea, 0xa3, 0x15,
	0xcb, 0x22, 0xff, 0x68, 0x73, 0xe9, 0x4d, 0xfa, 0xe6, 0x37, 0xfa, 0x46, 0xc3, 0x07, 0xbd, 0x28,
	0x4f, 0xbc, 0x80, 0xa7, 0xcf, 0x2c, 0x2a, 0x84, 0xaf, 0x18, 0x4f, 0xc7, 0x99, 0xe0, 0x8a, 0x63,
	0x14, 0xe5, 0x49, 0xa5, 0x93, 0x13, 0xf8, 0x3f, 0xcb, 0x93, 0xdb, 0x5d, 0x68, 0x51, 0x2c, 0x65,
	0x20, 0xd8, 0x92, 0xce, 0x7d, 0xe1, 0xaf, 0x24, 0x79, 0xb3, 0xa0, 0x77, 0xc8, 0x3c, 0x50, 0x29,
	0xfd, 0x88, 0xe2, 0x0b, 0x68, 0xc8, 0x20, 0xa6, 0x2b, 0xdf, 0xb1, 0x86, 0xd6, 0xa8, 0x35, 0xe9,
	0x8e, 0x37, 0x4f, 0x8f, 0x67, 0x79, 0xb2, 0xd0, 0x35, 0xd7, 0x30, 0xf8, 0x1a, 0x10, 0x4d, 0xc3,
	0x8c, 0xb3, 0x54, 0x49, 0xa7, 0x36, 0xb4, 0x47, 0xad, 0xc9, 0xef, 0xfd, 0x86, 0x3b, 0x53, 0x76,
	0xb7, 0x20, 0x9e, 0xc2, 0x4f, 0xbf, 0x50, 0xb1, 0x97, 0x09, 0xfe, 0xc2, 0x42, 0x2a, 0xa4, 0x63,
	0xeb, 0xd6, 0xfe, 0x7e, 0xeb, 0xb4, 0x50, 0xf1, 0xdc, 0x20, 0x6e, 0xdb, 0xdf, 0xb9, 0x49, 0xf2,
	0x0f, 0xd0, 0x66, 0x1a, 0xdc, 0x01, 0x3b, 0xca, 0x13, 0x3d, 0x30, 0x72, 0xcb, 0x23, 0x79, 0x82,
	0xd6, 0x8e, 0x37, 0xc6, 0x50, 0x8f, 0xb9, 0x54, 0x86, 0xd0, 0x67, 0x7c, 0x03, 0xf5, 0xf2, 0x49,
	0xa7, 0xa6, 0xbf, 0x79, 0xf6, 0xf1, 0xd4, 0xe5, 0x08, 0x34, 0x55, 0x2c, 0xd0, 0x3b, 0x72, 0x75,
	0x07, 0x49, 0xe0, 0xcf, 0xa7, 0x08, 0x1e, 0x00, 0xd2, 0x7f, 0x53, 0xeb, 0x8c, 0x1a, 0xbf, 0x66,
	0x29, 0x3c, 0xae, 0x33, 0x8a, 0xff, 0x56, 0x45, 0x2e, 0x98, 0x5a, 0x6b, 0x63, 0xe4, 0x6e, 0x05,
	0xdc, 0x85, 0xef, 0x32, 0xe0, 0x19, 0x75, 0x6c, 0x5d, 0xa9, 0x2e, 0xe4, 0xd5, 0x82, 0x5f, 0x07,
	0xcb, 0xf8, 0x8a, 0xc9, 0x00, 0x50, 0x90, 0x30, 0x9a, 0x2a, 0x8f, 0x85, 0xc6, 0xa8, 0x59, 0x09,
	0xf7, 0x21, 0x3e, 0x85, 0xb6, 0x29, 0x4a, 0x1a, 0x08, 0xaa, 0x9c, 0xba, 0x06, 0x7e, 0x54, 0xe2,
	0x42, 0x6b, 0x13, 0x09, 0x9d, 0xc3, 0xf0, 0x60, 0x0f, 0xd0, 0x26, 0x64, 0xf8, 0x7c, 0x7f, 0x97,
	0xc7, 0xa2, 0xd8, 0x27, 0x47, 0x58, 0x13, 0x49, 0xf2, 0xed, 0xd2, 0x5a, 0x36, 0x74, 0xce, 0xaf,
	0xde, 0x03, 0x00, 0x00, 0xff, 0xff, 0x73, 0x46, 0xe9, 0x32, 0x02, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GqlConfigurationClient is the client API for GqlConfiguration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GqlConfigurationClient interface {
	Subscribe(ctx context.Context, in *GqlConfigurationSubscribeParams, opts ...grpc.CallOption) (GqlConfiguration_SubscribeClient, error)
}

type gqlConfigurationClient struct {
	cc *grpc.ClientConn
}

func NewGqlConfigurationClient(cc *grpc.ClientConn) GqlConfigurationClient {
	return &gqlConfigurationClient{cc}
}

func (c *gqlConfigurationClient) Subscribe(ctx context.Context, in *GqlConfigurationSubscribeParams, opts ...grpc.CallOption) (GqlConfiguration_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GqlConfiguration_serviceDesc.Streams[0], "/gqlconfig.GqlConfiguration/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &gqlConfigurationSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GqlConfiguration_SubscribeClient interface {
	Recv() (*GqlConfigurationMessage, error)
	grpc.ClientStream
}

type gqlConfigurationSubscribeClient struct {
	grpc.ClientStream
}

func (x *gqlConfigurationSubscribeClient) Recv() (*GqlConfigurationMessage, error) {
	m := new(GqlConfigurationMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GqlConfigurationServer is the server API for GqlConfiguration service.
type GqlConfigurationServer interface {
	Subscribe(*GqlConfigurationSubscribeParams, GqlConfiguration_SubscribeServer) error
}

// UnimplementedGqlConfigurationServer can be embedded to have forward compatible implementations.
type UnimplementedGqlConfigurationServer struct {
}

func (*UnimplementedGqlConfigurationServer) Subscribe(req *GqlConfigurationSubscribeParams, srv GqlConfiguration_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterGqlConfigurationServer(s *grpc.Server, srv GqlConfigurationServer) {
	s.RegisterService(&_GqlConfiguration_serviceDesc, srv)
}

func _GqlConfiguration_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GqlConfigurationSubscribeParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GqlConfigurationServer).Subscribe(m, &gqlConfigurationSubscribeServer{stream})
}

type GqlConfiguration_SubscribeServer interface {
	Send(*GqlConfigurationMessage) error
	grpc.ServerStream
}

type gqlConfigurationSubscribeServer struct {
	grpc.ServerStream
}

func (x *gqlConfigurationSubscribeServer) Send(m *GqlConfigurationMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _GqlConfiguration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gqlconfig.GqlConfiguration",
	HandlerType: (*GqlConfigurationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _GqlConfiguration_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gql_configuration.proto",
}
