type Query {
    hello: String @stub(value: "world")
}

directive @stub(value: String) on FIELD_DEFINITION

input HttpNameValue {
    name: String!
    value: String!
}

directive @http(
    url: String!
    method: String
    contentType: String
    query: [HttpNameValue!]
    body: [HttpNameValue!]
    timeout: Int
    headers: [HttpNameValue!]
) on FIELD_DEFINITION

enum ContentTypes {
    json
}

input NameValue {
    name: String!
    value: String!
}

directive @rest(
    url: String!
    method: String
    contentType: ContentTypes
    bodyArg: String
    query: [NameValue!]
    headers: [NameValue!]
    timeoutMs: Int
) on FIELD_DEFINITION

directive @select(path: [String!]!) on FIELD_DEFINITION

directive @gql(
    url: String!
    queryName: String!
    arguments: String = ""
) on FIELD_DEFINITION

scalar JSON

directive @exportAs(
    key: String!
) on FIELD_DEFINITION