type Query {
  hello: String @stub(value: "world")
}

directive @stub(value: String) on FIELD_DEFINITION
directive @log on FIELD_DEFINITION
directive @overrideContext(value: String) on FIELD_DEFINITION

input HttpNameValue {
  name: String!
  value: String!
}

directive @http(
  url: String!
  method: String
  contentType: String
  query: [HttpNameValue!]
  body: [HttpNameValue!]
  timeout: Int
  headers: [HttpNameValue!]
) on FIELD_DEFINITION

directive @select(path: [String!]!) on FIELD_DEFINITION
directive @alias(from: String!) on FIELD_DEFINITION
