# agogos namespace
k8s_yaml('../examples/kubernetes/deployments/infra/namespace.yaml')

# agogos crds
k8s_yaml(
    listdir('../remote-sources/kubernetes/src/crd')
)

# mocks
k8s_yaml(
    listdir('../examples/kubernetes/deployments/mocks'),
)

# agogos deployments, roles & secrets
k8s_yaml(
    listdir('../examples/kubernetes/deployments/infra'),
)

# user namespace & services
k8s_yaml('../examples/kubernetes/deployments/services/user-namespace.yaml')
k8s_yaml(listdir('../examples/kubernetes/deployments/services/user'))
k8s_yaml(listdir('../examples/kubernetes/deployments/services/user-subscription'))

# e2e tests
k8s_yaml('./e2e.k8s.yaml')

docker_build('soluto/agogos-graphql-gateway', '../services/graphql-server')
docker_build('soluto/agogos-registry', '../services/registry')
docker_build('soluto/agogos-gql-controller', '../remote-sources/kubernetes')
docker_build('e2e', '.')

k8s_resource('e2e')