type Department {
  id: ID!
  name: String!
}

type Employee {
  id: ID!
  name: String!
}

type Query {
  departments: [Department!]!
  department(id: ID!): Department!
  employees: [Employee!]!
  employee(id: ID!): Employee!
}
