name: PR

on:
  pull_request:
    paths:
      - services/**
      - .github/workflows/pr.yaml
    branches-ignore:
      - master

  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: npm ci
        run: npm ci
        working-directory: services

      - name: type check
        run: npm run type-check
        working-directory: services

      - name: npm run unit & integration test
        run: npm run test -- --silent
        working-directory: services

      - name: npm run blackbox test
        run: npm run test:blackbox -- --silent
        working-directory: services

      - name: npm run e2e test
        run: npm run test:e2e -- --silent
        working-directory: services
